name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Neovim
        run: |
          sudo apt-get update
          sudo apt-get install -y neovim

      - name: Install test dependencies
        run: |
          mkdir -p .deps
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim.git .deps/plenary.nvim

      - name: Run tests
        run: |
          nvim --headless -u tests/minimal_init.lua \
            -c "lua require('plenary.test_harness').test_directory('tests', { minimal_init = 'tests/minimal_init.lua' })" \
            -c "qa"
